apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  name: my-vm
  uid: "5121287c6564adee"
spec:
  image:
    oci: weaveworks/ignite-ubuntu:latest
  cpus: 1
  diskSize: 1GB
  memory: 512MB
  ssh: {}
