apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2019-12-02T16:44:13Z"
  name: my-vm
  uid: 5121287c6564adee
spec:
  cpus: 1
  diskSize: 1GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.47
  memory: 512MB
  network: {}
  ssh: true
  storage: {}
status:
  image:
    id: null
    size: 0B
  kernel:
    id: null
    size: 0B
  running: true
